quantity = int(input('Enter the quantity of product'))
value = int(input('Enter the value of product'))
discount = int(input('Enter the discount amount'))
discount_per = float(discount / 100)
tax = int(input('Enter the tax rate'))
tax_per = float(tax / 100) 
amount = float(quantity * value + tax - discount_per)
print('quantity of product', quantity)
print('price of product', value)
print('your discount',discount_per)
print('your tax', tax_per)
print('you have to pay', amount)
